env:
  node: true
  browser: true
  es2021: true
extends: 
  - 'airbnb-base'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-console: 0
  import/extension: 0
  linebreak-style: 0
  no-await-in-loop: 0
  # allowForLoopAfterthoughts: true
